name: iOS starter workflow

on:
  push:
    branches: [ detox-setup ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Set up Node
      run: |
        npm install -g react-native-cli
        npm install -g detox-cli
    - name: Install Detox
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: npm install
      run: npm install

    - name: install pods
      run: cd ios && pod install && cd ..

    - name: Detox Build
      run: detox build --configuration ios.sim.release
    - name: Detox Test
      run: detox test --configuration ios.sim.release --cleanup
