name: Testing how to run the emulator on Android and also some caching

on:
  push:
    branches: [ emul ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: npm install if not cached
        run: npm install

      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g detox-cli
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          avd-name: Pixel_API_29_AOSP
          script: detox build --configuration android.emu.release && detox test --configuration android.emu.release --cleanup
