name: Testing how to run the emulator on Android and also some caching

on:
  push:
    branches: [ emul ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: instal emulator and list available
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install emulator
          $ANDROID_HOME/tools/bin/sdkmanager "build-tools;29.0.3"
          $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-29;default;x86_64"
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: grep for a 29 image
        run: |
          sdkmanager --list | grep "android-29"
      - name: instal the actual image and create the emulator
        run: |
          $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_29_AOSP -d pixel --package "system-images;android-29;default;x86_64"