name: Testing how to run the emulator on Android and also some caching

on:
  push:
    branches: [ emul ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
      ENABLE_APP_VERSIONING: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: build detox app
        run: npx detox build --configuration android.emu.release
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          avd-name: Pixel_API_29_AOSP
          script: npx detox test --configuration android.emu.release --cleanup
