name: Testing how to run the emulator on Android and also some caching

on:
  push:
    branches: [ emul ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 15
        - uses: gradle/wrapper-validation-action@v1
        - uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
              key: ${{ runner.os }}-${{ github.job }}-${{ matrix.module }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

        - uses: actions/setup-node@v2
          with:
            node-version: '12'

      - name: npm install if not cached
        run: npm install
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          avd-name: Pixel_API_29_AOSP
          script: detox build --configuration android.emu.release && detox test --configuration android.emu.release --cleanup
