name: Testing how to run the emulator on Android and also some caching

on:
  push:
    branches: [ emul ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: instal emulator and list available
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install emulator
      - name: instal the actual image and create the emulator
        run: |
          $ANDROID_HOME/tools/bin/avdmanager list