name: Testing how to run the emulator on Android and also some caching

on:
  push:
    branches: [ emul ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: instal emulator and list available
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install emulator
      - name: instal the actual image and create the emulator
        run: |
          $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_29_AOSP -d pixel --package "system-images;android-29;default;x86_64"