name: Testing how to run on Git Tags

on:
  push:
    tags:
      - "v*-*"
      - "!v*-*-mark"
      - "!v*-*-steve"
      - "!v*-*-testone"
      - "!v*-*-workshop"
      - "!v*-*-prod"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
