name: Testing how to run on Git Tags

on:
  push:
    branches: [ emul ]
    tags:
      - "v*-*"
      - "!v*-*-mark"
      - "!v*-*-steve"
      - "!v*-*-testone"
      - "!v*-*-workshop"
      - "!v*-*-prod"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: node-cache
        id: nodecache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        if: steps.nodecache.outputs.cache-hit != 'true'
        run: npm install