name: Testing how to run on Git Tags

on:
  create:
    tags:
      - v[0-9]+-[0-9]+
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
